
#define REMOTECONTROL_ADDRESS 0x02FD

#define REMOTECONTROL_BUTTON_POWER	0x48
#define REMOTECONTROL_BUTTON_1		0x80
#define REMOTECONTROL_BUTTON_2		0x40
#define REMOTECONTROL_BUTTON_3		0xc0
#define REMOTECONTROL_BUTTON_4		0x20
#define REMOTECONTROL_BUTTON_5		0xA0
#define REMOTECONTROL_BUTTON_6		0x60
#define REMOTECONTROL_BUTTON_7		0xe0
#define REMOTECONTROL_BUTTON_8		0x10
#define REMOTECONTROL_BUTTON_9		0x90
#define REMOTECONTROL_BUTTON_0		0x00
